version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - setup_remote_docker
      - checkout
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/alpine/8.9.4-alpine && docker build -t godaddy/node:8.9.4-alpine-$version .;
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/alpine/9.7.1-alpine && docker build -t godaddy/node:9.7.1-alpine-$version .;
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/debian/8.9.4-debian && docker build -t godaddy/node:8.9.4-debian-$version .;
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/debian/9.7.1-debian && docker build -t godaddy/node:9.7.1-debian-$version .;

  deploy:
    docker:
      - image: circleci/node:8.9.4
    filters:
      tags:
        only: /v[0-9]+(\.[0-9]+)*/
    steps:
      - checkout
      - setup_remote_docker
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/alpine/8.9.4-alpine && docker push godaddy/node:8.9.4-alpine-$version;
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/alpine/9.7.1-alpine && docker push godaddy/node:9.7.1-alpine-$version;
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/debian/8.9.4-debian && docker push godaddy/node:8.9.4-debian-$version;
      - run: version=$(node -pe "($(cat package.json)).version"); cd generated-dockerfiles/debian/9.7.1-debian && docker push godaddy/node:9.7.1-debian-$version;

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
